name: my-CIML
on: [push]
permissions:
  contents: write
  security-events: write

jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python modeling_script.py
          echo "## Model metrics" > report.md
          cat results.txt >> report.md

          # Post reports as comments in GitHub PRs
          # cat results.txt >> report.md
          # cml comment create report.md

          cml comment create report.md