name: my-CIML
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Setup CML
        run: |
          curl -s https://cml.dev/install.sh | sudo bash

      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python modeling_script.py
          echo "## Model metrics" > report.md
          cat results.txt >> report.md

          # Post reports as comments in GitHub PRs
          # cat results.txt >> report.md
          # cml comment create report.md

          cml comment create report.md